name: checkupdate

on:
  push:
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: 0 0-14 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Set proxy
        uses: w311ang/setproxy@main
        with:
          config: ${{ secrets.ss_config }}
          password: ${{ secrets.frp_auth }}
          redirect: ${{ secrets.frp_redirect }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ./
          key: build-${{ github.run_id }}
          restore-keys: |
            build-
      - name: Run
        env:
          logindata: ${{ secrets.logindata }}
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: |
            proxychains python -u main.py
          on_retry_command: sudo systemctl restart shadowsocks-libev-local@client; sleep 5s
      - uses: gautamkrishnar/keepalive-workflow@master
